language: c
script:
- make
- make test
- make janet-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz
compiler:
- clang
- gcc
os:
- linux
- osx
before_deploy:
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "$TRAVIS_BUILD_DIR/janet-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz"
  skip_cleanup: true
  draft: true
  on:
    tags: true
