version: 1.0.{build}
branches:
  only:
  - master
  - alpha
clone_folder: c:\projects\dst
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

before_build:
- cmd: |-
    build
build:
- cmd: |-
    build test
only_commits:
  files:
    - appveyor.yml
    - src/
