version: 1.0.{build}
branches:
  only:
  - master
  - stable
clone_folder: c:\projects\janet
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

install:
    - build_win
    - build_win test
    
build: off

only_commits:
  files:
    - appveyor.yml
    - src/

deploy:
  release: janet-v$(appveyor_build_version)
  description: 'The janet programming language'
  provider: GitHub
  auth_token:
    secure: c286b67f8b74b835b75ed62d2f5a28528850a690
  artifact: janet.exe
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
