image: freebsd/latest
packages:
  - gmake
  - gcc
sources:
  - https://github.com/janet-lang/janet.git
tasks:
  - build: |
      cd janet
      gmake CC=gcc
      gmake test CC=gcc
      sudo gmake install CC=gcc
      gmake test-install CC=gcc
