image: freebsd/latest
packages:
  - gmake
  - gcc
tasks:
  - build: |
      cd janet
      gmake CC=gcc
      gmake test CC=gcc
      sudo gmake install CC=gcc
      gmake test-install CC=gcc
      gmake test-amalg CC=gcc
